# Change these first
owner: nanoolabs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Nanoo Labs
    url: https://nanoolabs.dev
  - name: Nanoo Root
    url: https://root.nanoolabs.dev
  - name: Nanoo Webrings
    url: https://webrings.nanoolabs.dev
  - name: Nanoo Stack
    url: https://stack.nanoolabs.dev
  - name: Nanoo Docs
    url: https://docs.nanoolabs.dev
  - name: Nanoo CDN
    url: https://cdn.nanoolabs.dev

status-website:
  theme: dark
  cname: status.nanoolabs.dev
  logoUrl: https://cdn.nanoolabs.dev/brands/latest/nanoo-dark.svg
  name: "Nanoo Labs"
  introTitle: "**Nanoo Labs Status**"
  introMessage: "Real-time monitoring for our high-performance ecosystems and experimental platforms."
  themeUrl: https://raw.githubusercontent.com/nanoolabs/status/HEAD/assets/nanoo-upptime.css
  customHeadHtml: |
    <link rel="stylesheet" href="https://unpkg.com/@nlbs/css">
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Nanoo
      href: https://nanoolabs.dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
