# Change these first
owner: nanoolabs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
cname: status.nanoolabs.dev

sites:
  - name: Nanoo Labs
    url: https://nanoolabs.dev
  - name: Nanoo Root
    url: https://root.nanoolabs.dev
  - name: Nanoo Webrings
    url: https://webrings.nanoolabs.dev
  - name: Nanoo Stack
    url: https://stack.nanoolabs.dev
  - name: Nanoo Docs
    url: https://docs.nanoolabs.dev
  - name: Nanoo CDN
    url: https://cdn.nanoolabs.dev

status-website:
  cname: status.nanoolabs.dev
  logoUrl: https://raw.githubusercontent.com/nanoolabs/changelog/main/brands/v.1.5.0/nanoo-dark.svg
  name: "Nanoo Labs | Health"
  introTitle: "**Nanoo Labs Health**"
  introMessage: "Real-time monitoring for our high-performance ecosystems and experimental platforms. Built fast, simple, and scalable."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Nanoo Labs
      href: https://nanoolabs.dev
  theme: dark
  themeUrl: /assets/nanoo-theme.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
